version: "3.8"

services:
  front-end:
    depends_on:
      - api
    build: ./front-end
    container_name: huskyreads_front_end
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./front-end/app:/app
    command: /app/entrypoint.sh

  api:
    # depends_on:
    # - db
    build: ./back-end
    container_name: huskyreads_api
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./back-end/app:/app
    command: /app/entrypoint.sh

  # db:
  #   image: mysql:8.0.26
  #   container_name: huskyreads_db
  #   restart: always
  #   environment:
  #     MYSQL_HOST: "localhost"
  #     MYSQL_DATABASE: "huskyreads"
  #     MYSQL_USER: "root"
  #     MYSQL_PASSWORD: "root"
  #     MYSQL_ROOT_PASSWORD: "root"
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/var/lib/mysql
  #     - db_logs:/var/log/mysql

volumes:
  db_data:
  db_logs: